# ==========================================
# Tmux configuration file
# ==========================================

# Ctrl + a for new prefix key
unbind C-b
set -g prefix C-a

# Toggle status line visibility with prefix + a
bind a set-option -g status

# Reload tmux configuration with prefix + r
bind r source-file ~/.tmux.conf

# Allow tmux clipboard to copy to system clipboard
set -s set-clipboard on

# Themes
set -g status off

set -g mode-style "fg=default,bg=brightblack"
set -g status-style "bg=default,fg=#d8dee9"
set -g message-style "bg=default,fg=#d8dee9"
